# -*- coding: utf-8 -*-
"""Credit_Risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DI-zCNq6LtTq2waY3VnE4NHHPvQ0z39
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

from sklearn.calibration import calibration_curve
from scipy.stats import ks_2samp
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Data Understanding
df = pd.read_csv("credit_risk_dataset.csv")

print(df.shape)
print(df.info())
print(df.isnull().sum())

"""Dataset Overview

The dataset contains 32,581 observations and 12 features.

variables

Variable Types

*   Numerical Variables: Age, Income, Employment Length, Loan Amount, Interest Rate, Loan Percent Income, Credit History Length.
Categorical Variables: Home Ownership, Loan Intent,
*   Loan Grade, Previous Default Flag.
*   Target Variable: loan_status (Default / Non-default).

Two variables contain missing values:
*   person_emp_length → 895 missing (~2.75%)
*   loan_int_rate → 3116 missing (~9.56%)

Imputation Strategy
*   Employment Length: Filled using median since the variable is skewed and contains outliers.
*   Loan Interest Rate: Filled using loan-grade-wise median to preserve lender pricing structure across risk grades.
"""

# Target Distribution
print(df['loan_status'].value_counts())

# Missing Variables Treatment

# Employment Length -> Median
df['person_emp_length'] = df['person_emp_length'].fillna(
    df['person_emp_length'].median()
)

# Interest Rate -> Grade-wise Median
df['loan_int_rate'] = df.groupby('loan_grade')['loan_int_rate'].transform(
    lambda x: x.fillna(x.median())
)

# Borrower Risk Profiling (EDA)
fig, axes = plt.subplots(2, 2, figsize=(14,10))

df.groupby('loan_grade')['loan_status'].mean().plot(
    kind='bar', ax=axes[0,0]
)

df.groupby('loan_intent')['loan_status'].mean().plot(
    kind='bar', ax=axes[0,1]
)

df.groupby('person_home_ownership')['loan_status'].mean().plot(
    kind='bar', ax=axes[1,0]
)

df.groupby('cb_person_default_on_file')['loan_status'].mean().plot(
    kind='bar', ax=axes[1,1]
)

plt.tight_layout()
plt.show()

# Train-Test Split
X = df.drop('loan_status', axis=1)
y = df['loan_status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Outlier Visualization (Before Treatment)
cap_cols = [
    'person_income',
    'loan_amnt',
    'person_emp_length'
]

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, col in enumerate(cap_cols):
    sns.boxplot(y=X_train[col], ax=axes[i])
    axes[i].set_title(f"Before Treatment: {col}")

plt.tight_layout()
plt.show()

# Outlier Treatment (Using IQR)
for col in cap_cols:

    Q1 = X_train[col].quantile(0.25)
    Q3 = X_train[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - (1.5 * IQR)
    upper = Q3 + (1.5 * IQR)

    X_train[col] = X_train[col].clip(lower, upper)
    X_test[col] = X_test[col].clip(lower, upper)

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for i, col in enumerate(cap_cols):
    sns.boxplot(y=X_train[col], ax=axes[i])
    axes[i].set_title(f"After Treatment: {col}")

plt.tight_layout()
plt.show()

# VIF Check
vif_cols = [
    'person_age',
    'person_income',
    'person_emp_length',
    'loan_amnt',
    'loan_int_rate',
    'loan_percent_income',
    'cb_person_cred_hist_length'
]

vif_data = X_train[vif_cols]

vif_df = pd.DataFrame()
vif_df["Feature"] = vif_cols
vif_df["VIF"] = [
    variance_inflation_factor(vif_data.values, i)
    for i in range(vif_data.shape[1])
]

print(vif_df)

# Dropping features if vif > 10
X_train = X_train.drop(['person_age'], axis=1)
X_test = X_test.drop(['person_age'], axis=1)

X_train = X_train.drop(['person_income'], axis=1)
X_test = X_test.drop(['person_income'], axis=1)

X_train = X_train.drop(['loan_amnt'], axis=1)
X_test = X_test.drop(['loan_amnt'], axis=1)

# Dfining Features
cat_cols = [
    'person_home_ownership',
    'loan_intent',
    'loan_grade',
    'cb_person_default_on_file'
]

num_cols = [
    'person_emp_length',
    'loan_int_rate',
    'loan_percent_income',
    'cb_person_cred_hist_length'
]

# Preprocessing
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(drop='first'), cat_cols),
    ('num', StandardScaler(), num_cols)
])

# Logistic model
model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

# Predictions
# PD=P(Y=1∣X)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

# Model Evaluation
# Classification Report
print(classification_report(y_test, y_pred))

# ROC AUC
auc = roc_auc_score(y_test, y_prob)
print("ROC AUC:", auc)

# Gini
# Gini=2×AUC−1
gini = 2*auc - 1
print("Gini:", gini)

# KS Statistic
# KS=max(F1​(x)−F0​(x))

ks = ks_2samp(
    y_prob[y_test==1],
    y_prob[y_test==0]
)

print("KS:", ks.statistic)

# Threshold optimization
# Instead of 0.5; Use KS-max threshold:

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

ks_scores = tpr - fpr
optimal_idx = np.argmax(ks_scores)

optimal_threshold = thresholds[optimal_idx]

print("Optimal Threshold:", optimal_threshold)

y_pred_optimal = (y_prob >= optimal_threshold).astype(int)

print(classification_report(y_test, y_pred_optimal))

# Calibration Check
prob_true, prob_pred = calibration_curve(
    y_test,
    y_prob,
    n_bins=10,
    strategy='quantile'
)

plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0,1],[0,1], linestyle='--')
plt.title("Calibration Curve")
plt.show()

# Odds Ratio Analysis
encoded_cols = (
    model.named_steps['preprocessor']
    .named_transformers_['cat']
    .get_feature_names_out(cat_cols)
)

feature_names = list(encoded_cols) + num_cols

coefficients = model.named_steps['classifier'].coef_[0]

coef_df = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients
})

coef_df['Odds_Ratio'] = np.exp(coef_df['Coefficient'])

coef_df = coef_df.sort_values(
    by='Odds_Ratio',
    ascending=False
)

print(coef_df)

"""Interpretation logic

Odds ratio formula:

Odds Ratio=e^β

Interpretation:
*   Odd Ratio > 1 → increases default odds
*   Odd Ratio < 1 → decreases default odds
*   Odd Ratio = 1 → neutral
"""

# If: cb_person_default_on_file_Y = 0.04
# Means: Borrowers with prior default history have 96% lower odds of default
# relative to the reference group.

# Log odds
coef_df['Log_Odds_Ratio'] = np.log(coef_df['Odds_Ratio'])

# Positive risk drivers
positive_drivers = coef_df[
    coef_df['Log_Odds_Ratio'] > 0
].sort_values(
    by='Log_Odds_Ratio',
    ascending=False
).head(10)

# Negative (protective) drivers
negative_drivers = coef_df[
    coef_df['Log_Odds_Ratio'] < 0
].sort_values(
    by='Log_Odds_Ratio',
    ascending=True
).head(10)

# Subplots
fig, axes = plt.subplots(1, 2, figsize=(18, 8))

# Positive subplot
sns.barplot(
    data=positive_drivers,
    x='Log_Odds_Ratio',
    y='Feature',
    ax=axes[0]
)

axes[0].axvline(
    x=0,
    linestyle='--'
)

axes[0].set_title("Top Positive Risk Drivers")
axes[0].set_xlabel("Log Odds Ratio")
axes[0].set_ylabel("Feature")

# Negative subplot
sns.barplot(
    data=negative_drivers,
    x='Log_Odds_Ratio',
    y='Feature',
    ax=axes[1]
)

axes[1].axvline(
    x=0,
    linestyle='--'
)

axes[1].set_title("Top Negative (Protective) Drivers")
axes[1].set_xlabel("Log Odds Ratio")
axes[1].set_ylabel("Feature")

plt.tight_layout()
plt.show()

# PSI (for stability monitoring)

# PSI formula: PSI=∑(Actual%−Expected%)ln(Expected% / Actual%)

def calculate_psi(expected, actual, buckets=10):

    breakpoints = np.percentile(
        expected,
        np.arange(0, 101, 100 / buckets)
    )

    expected_counts = np.histogram(expected, bins=breakpoints)[0]
    actual_counts = np.histogram(actual, bins=breakpoints)[0]

    expected_perc = expected_counts / len(expected)
    actual_perc = actual_counts / len(actual)

    expected_perc = np.where(expected_perc == 0, 0.0001, expected_perc)
    actual_perc = np.where(actual_perc == 0, 0.0001, actual_perc)

    psi_values = (
        (actual_perc - expected_perc)
        * np.log(actual_perc / expected_perc)
    )

    return np.sum(psi_values)

    # Use: Train PD vs Test PD

train_prob = model.predict_proba(X_train)[:, 1]
test_prob = model.predict_proba(X_test)[:, 1]

psi_score = calculate_psi(train_prob, test_prob)

print("PSI:", psi_score)

"""Interpret:
*   < 0.1 → stable
*   0.1–0.25 → moderate shift
*   0.25 → significant drift
"""